blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/KRTirtho/spotube/discussions/new?category=q-a
    about: The place for questions, support and feature requests
